name: Bug Report
description: Report a bug or issue with an existing integration
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🐛

        Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: integration
    attributes:
      label: Integration
      description: Which integration is affected?
      options:
        - "Agent Frameworks"
        - "E-commerce"
        - "Developer Tools"
        - "Middleware"
        - "Protocol Bridges"
        - "SDK"
        - "Other"
      value: ""
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "Describe the bug..."
      value: ""
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: ""
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "Describe what should happen..."
      value: ""
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Describe what actually happened..."
      value: ""
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      placeholder: |
        - OS: [e.g. macOS, Windows, Linux]
        - Node.js version: [e.g. 18.17.0]
        - Integration version: [e.g. 1.0.0]
        - Browser: [e.g. Chrome, Safari]
      value: ""
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Any relevant logs or error messages
      placeholder: "Paste any error messages or logs here..."
      value: ""
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "Add any other context about the problem here..."
      value: ""
