name: Feature Request
description: Suggest a new integration or feature
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 💡

        Please provide as much detail as possible about what you'd like to see built.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What category does this feature belong to?
      options:
        - "Agent Frameworks"
        - "E-commerce"
        - "Developer Tools"
        - "Middleware"
        - "Protocol Bridges"
        - "SDK"
        - "Other"
      value: ""
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature
      placeholder: "Describe the feature you'd like to see..."
      value: ""
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would this feature be used?
      placeholder: "Describe the specific use case and how it would benefit users..."
      value: ""
    validations:
      required: true
  - type: textarea
    id: tech-stack
    attributes:
      label: Technology Stack
      description: What technologies/frameworks would be involved?
      placeholder: "JavaScript, Python, Go, etc."
      value: ""
  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Any ideas on how this could be implemented?
      placeholder: "Share any implementation ideas or approaches..."
      value: ""
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered
      placeholder: "Describe any alternative solutions or workarounds..."
      value: ""
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the feature request
      placeholder: "Add any other context, screenshots, or examples..."
      value: ""
