name: CI/CD Pipeline
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
        python-version: [3.9, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Node.js dependencies
        run: |
          find . -name "package.json" -not -path "./node_modules/*" | while read file; do
            dir=$(dirname "$file")
            echo "Installing dependencies in $dir"
            cd "$dir" && npm ci --only=production
            cd - > /dev/null
          done

      - name: Install Python dependencies
        run: |
          find . -name "requirements.txt" | while read file; do
            dir=$(dirname "$file")
            echo "Installing dependencies in $dir"
            cd "$dir" && pip install -r requirements.txt
            cd - > /dev/null
          done

      - name: Lint JavaScript/TypeScript
        run: |
          find . -name "package.json" -not -path "./node_modules/*" | while read file; do
            dir=$(dirname "$file")
            if [ -f "$dir/.eslintrc.js" ] || [ -f "$dir/.eslintrc.json" ]; then
              echo "Linting JavaScript/TypeScript in $dir"
              cd "$dir" && npm run lint || echo "No lint script found"
              cd - > /dev/null
            fi
          done

      - name: Lint Python
        run: |
          find . -name "*.py" | while read file; do
            echo "Linting Python file: $file"
            python -m flake8 "$file" || echo "Flake8 not available"
          done

      - name: Test JavaScript/TypeScript
        run: |
          find . -name "package.json" -not -path "./node_modules/*" | while read file; do
            dir=$(dirname "$file")
            if [ -f "$dir/test" ] || [ -f "$dir/tests" ] || [ -f "$dir/__tests__" ]; then
              echo "Running tests in $dir"
              cd "$dir" && npm test || echo "No test script found"
              cd - > /dev/null
            fi
          done

      - name: Test Python
        run: |
          find . -name "test_*.py" -o -name "*_test.py" | while read file; do
            dir=$(dirname "$file")
            echo "Running Python tests in $dir"
            cd "$dir" && python -m pytest "$file" || echo "Pytest not available"
            cd - > /dev/null
          done

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  integration-tests:
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup test environment
        run: |
          # Set up test environment variables
          echo "APORT_API_KEY=test_key" >> $GITHUB_ENV
          echo "APORT_BASE_URL=https://api.aport.io" >> $GITHUB_ENV

      - name: Run integration tests
        run: |
          # Look for integration test files
          find . -name "*integration*test*" -o -name "*e2e*test*" | while read file; do
            echo "Running integration test: $file"
            # Add specific test commands based on file type
            if [[ "$file" == *.js ]]; then
              node "$file" || echo "Integration test failed: $file"
            elif [[ "$file" == *.py ]]; then
              python "$file" || echo "Integration test failed: $file"
            fi
          done

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [lint-and-test, security-scan, integration-tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build packages
        run: |
          # Build any packages that need building
          find . -name "package.json" -not -path "./node_modules/*" | while read file; do
            dir=$(dirname "$file")
            if [ -f "$dir/build" ] || [ -f "$dir/dist" ]; then
              echo "Building package in $dir"
              cd "$dir" && npm run build || echo "No build script found"
              cd - > /dev/null
            fi
          done

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment"
          # Add deployment commands here

      - name: Notify team
        run: |
          echo "📢 Notifying team of successful deployment"
          # Add notification commands here
